// SPDX-License-Identifier: GPL-3.0
pragma solidity 0.8.9;
pragma abicoder v2;

import "@chainlink/contracts/src/v0.8/KeeperCompatible.sol";

import "./interfaces/ILendingMarket.sol";

/**
 * @title LiquidationBot
 */
contract LiquidationBot is KeeperCompatible {
    uint256 public constant MAX_SEARCH_COUNT = 100;
    uint256 public constant MAX_LIQUIDATION_COUNT = 3;
    ILendingMarket public immutable lendingMarket;

    constructor(address _lendingMarket) {
        lendingMarket = ILendingMarket(_lendingMarket);
    }

    function checkUpkeep(bytes calldata checkData)
        external
        view
        override
        returns (bool upkeepNeeded, bytes memory performData)
    {
        address token = abi.decode(checkData, (address));
        uint256 userCount = lendingMarket.getUserCount(token);
        for (uint256 i = 0; i < userCount; i++) {
            address user = lendingMarket.getUserAt(token, i);
            if (lendingMarket.liquidatable(user, token)) {
                performData = abi.encode(performData, user);
            }
        }

        upkeepNeeded = performData.length != 0;
    }

    function performUpkeep(
        bytes calldata /* performData */
    ) external override {
        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }
}
